import { z } from 'zod';
import type { JournalEntry } from './plan.js';

/**
 * The migration journal, parsed rather than trusted.
 *
 * drizzle/meta/_journal.json is generated by drizzle-kit: it is committed, but
 * we do not write it, and §4's rule — external data is parsed, never cast —
 * covers a tool's output as much as an API's. The failure this guards against
 * is quiet and expensive: a renamed field would leave the plan seeing zero
 * migrations and a run reporting "nothing to do" against a database that needs
 * every one of them.
 *
 * Only three fields are kept. `version` and `breakpoints` are drizzle-kit's
 * business, and carrying them would couple this module to a shape it does not
 * use.
 */
const journalSchema = z.object({
  entries: z.array(
    z.object({
      idx: z.number().int().nonnegative(),
      when: z.number().int().positive(),
      tag: z.string().min(1),
    }),
  ),
});

export function parseJournal(source: unknown): JournalEntry[] {
  const result = journalSchema.safeParse(source);

  if (!result.success) {
    throw new Error(
      'drizzle/meta/_journal.json does not have the expected shape.\n' +
        result.error.issues
          .map((issue) => `  - ${issue.path.join('.')}: ${issue.message}`)
          .join('\n') +
        '\nIt is generated by drizzle-kit: check whether its format changed ' +
        'before touching anything else.',
    );
  }

  return result.data.entries.map((entry) => ({ idx: entry.idx, when: entry.when, tag: entry.tag }));
}
